
# DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost/vxserver?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 12345
    driver-class-name:  com.mysql.jdbc.Driver


server:
  port: 8081

#mybatis mapper
mybatis:
    mapper-locations: classpath*:mappers/*.xml
    typeAliasesPackage: com.ant.vxserver.pojo
    mapper-generator: src/main/resources/
    mapper-java: com.ant.vxserver.dao
    mapper-pojo: ./src/main/java

#weichat
weixin:
  app_id: wx5257aaa64a6401f0
  app_secret: e491abb27626fa5edeb0e864f3e40172
  app_url:  https://api.weixin.qq.com/sns/jscode2session


